### ISSUE TITLE
What is the ClientRect referring to in the code?

### ISSUE THREAD

**Issue by tirams** [RobertMenke/react-popover#2]
I'm trying to use this component and attempting to render the example html in Chrome but the ClientRect object referred to in the Popover component is not defined. Where is the definition of ClientRect??

**Comment by TimTruston** [comment]
Same issue here

**Comment by brenthosie** [comment]
@TechyTimo @tirams I opened [this PR](https://github.com/RobertMenke/react-popover/pull/3) in hopes to address this problem.

**Comment by RobertMenke** [comment]
@tirams @TechyTimo @brenthosie Sorry for taking so long to get back to you. For some reason, I never saw any of the back-and-forth in my email inbox. I've merged @brenthosie's PR in #3 and that should fix the issue.

Thank you all of using and contributing to this component!
