### ISSUE TITLE
Support for React Native

### ISSUE THREAD

**Issue by AdamGerthel** [RobertMenke/react-popover#7]
I noticed that `react-dom` is a requirement, so I'm assuming that React Native isn't supported. Do you have any idea whether it would be possible to support?

**Comment by RobertMenke** [comment]
@AdamGerthel The approach I'm using for positioning here is very specific to the DOM (https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect). 

Positioning/tooltips are very different on mobile and the approach would need to be fundamentally different. Feel free to re-open if you want to keep the dialog going :).
